# Generated by Django 3.2.25 on 2024-08-31 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0002_auto_20240828_2147'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='type',
            field=models.CharField(choices=[('BV', 'beverage'), ('AP', 'appetizer'), ('MA', 'main'), ('SD', 'side')], default='BV', max_length=2),
        ),
        migrations.AlterField(
            model_name='item',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
