# Generated by Django 3.2.25 on 2024-08-31 11:29

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0003_auto_20240831_1052'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 31, 11, 29, 4, 603262, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='item',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 31, 11, 29, 4, 603418, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='item',
            name='veg_nonveg',
            field=models.CharField(choices=[('Veg', 'veg'), ('Non-Veg', 'non-veg')], default='Veg', max_length=7),
        ),
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.CharField(max_length=20),
        ),
    ]
