# Generated by Django 3.2.25 on 2024-08-31 11:53

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0004_auto_20240831_1129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 31, 11, 53, 30, 117750, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='item',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 31, 11, 53, 30, 117909, tzinfo=utc)),
        ),
    ]
