# Generated by Django 3.2.25 on 2024-09-01 16:30

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('item', '0005_auto_20240901_1216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 1, 16, 30, 46, 566468, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='item',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 1, 16, 30, 46, 566656, tzinfo=utc)),
        ),
    ]
