# Generated by Django 3.2.25 on 2024-08-31 12:13

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0006_auto_20240831_1155'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 31, 12, 13, 53, 398666, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='item',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 31, 12, 13, 53, 398833, tzinfo=utc)),
        ),
    ]
