# Generated by Django 3.2.25 on 2024-09-02 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0007_auto_20240831_1213'),
        ('item', '0007_auto_20240901_1704'),
    ]

    operations = [
    ]
