# Generated by Django 3.2.25 on 2024-09-02 19:23

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0008_merge_0007_auto_20240831_1213_0007_auto_20240901_1704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 2, 19, 23, 50, 529207, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='item',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 2, 19, 23, 50, 529396, tzinfo=utc)),
        ),
    ]
