# Generated by Django 3.2.25 on 2024-09-02 19:43

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0010_auto_20240902_1928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 2, 19, 43, 40, 643498, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='item',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 2, 19, 43, 40, 643669, tzinfo=utc)),
        ),
    ]
