# Generated by Django 3.2.25 on 2024-09-18 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_alter_cart_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='prev_quantity',
            field=models.IntegerField(default=0),
        ),
    ]
