# Generated by Django 3.2.25 on 2024-09-01 18:27

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 1, 18, 27, 16, 342406, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='order',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 1, 18, 27, 16, 342562, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 1, 18, 27, 16, 342406, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 1, 18, 27, 16, 342562, tzinfo=utc)),
        ),
    ]
