# Generated by Django 3.2.25 on 2024-09-01 18:29

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_auto_20240901_1827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 1, 18, 29, 10, 911856, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='order',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 1, 18, 29, 10, 911989, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 1, 18, 29, 10, 911856, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 1, 18, 29, 10, 911989, tzinfo=utc)),
        ),
    ]
